import os
from ultralytics import YOLO

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Set your absolute or relative paths here
DATASET_PHASE_1 = "step1.yaml"
DATASET_PHASE_2 = "step2.yaml"
OUTPUT_BASE_DIR = "runs" # Where the models will be saved

# Set your base model here
BASE_MODEL = "yolo11s.pt" 
# ==========================================
# 2. PHASE 1: SIMULATION BASE TRAINING
# ==========================================
def run_phase_1():
    print("\n" + "="*50)
    print("🚀 STARTING PHASE 1: SIMULATION TRAINING")
    print("="*50 + "\n")
    
    # Load the base YOLO11s model
    model = YOLO(BASE_MODEL)
    
    # Train Phase 1
    # Adjust 'batch' to your RTX 2070 Super's VRAM. 16 is safe, or try 32.
    results = model.train(
        data=DATASET_PHASE_1,
        project=OUTPUT_BASE_DIR,
        name="phase1_sim",
        
        # Core Parameters
        epochs=150,
        patience=20,
        batch=48, 
        workers=4,
        imgsz=640,
        device=0, # Use GPU 0
        
        # Learning Rate & Optimizer
        optimizer="auto",
        lr0=0.01,
        
        # Aggressive Augmentations for Simulation
        mosaic=1.0,
        mixup=0.1,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4
    )
    
    # Ultralytics automatically saves the best weights here
    best_weights_path = os.path.join(OUTPUT_BASE_DIR, "phase1_sim", "weights", "best.pt")
    return best_weights_path

# ==========================================
# 3. PHASE 2: REAL-WORLD FINE-TUNING
# ==========================================
def run_phase_2(base_weights):
    print("\n" + "="*50)
    print(f"🚀 STARTING PHASE 2: FINE-TUNING (Base: {base_weights})")
    print("="*50 + "\n")
    
    # Check if Phase 1 completed successfully
    if not os.path.exists(base_weights):
        raise FileNotFoundError(f"Phase 1 weights not found at: {base_weights}")

    # Load the weights generated by Phase 1
    model = YOLO(base_weights)
    
    # Train Phase 2
    results = model.train(
        data=DATASET_PHASE_2,
        project=OUTPUT_BASE_DIR,
        name="phase2_real",
        
        # Core Parameters
        epochs=50,
        patience=10,
        batch=48,
        workers=4,
        imgsz=640,
        device=0,
        
        # Gentle Adaptation Parameters (Preventing Catastrophic Forgetting)
        lr0=0.0005,       # Lower learning rate
        cos_lr=True,      # Smooth learning rate curve
        warmup_epochs=5,  # Slow introduction to the new data
        freeze=10,        # Freeze the backbone
        
        # Reduced Augmentations
        mosaic=0.5,
        mixup=0.0
    )
    
    final_weights = os.path.join(OUTPUT_BASE_DIR, "phase2_real", "weights", "best.pt")
    print(f"\n✅ FULL PIPELINE COMPLETE! Final deployable model: {final_weights}")

# ==========================================
# 4. EXECUTION
# ==========================================
if __name__ == "__main__":
    try:
        # Run Phase 1 and get the path to the resulting weights
        phase_1_weights = run_phase_1()
        
        # Pass those weights directly into Phase 2
        run_phase_2(phase_1_weights)
        
    except Exception as e:
        print(f"\n❌ Pipeline failed: {e}")